import asyncio
import logging
from pathlib import Path

from openai import AsyncOpenAI

from config import settings

log = logging.getLogger(__name__)

REPORTS_DIR = Path("reports")

#----------QA Prompt------------------------------------------------------------
#instructing the model to return structured Markdown so the report is
#immediately usable without further post-processing.
_QA_SYSTEM_PROMPT = """\
You are a senior QA engineer evaluating an AI medical office phone agent.
Your job is to read call transcripts and identify bugs, quality issues, and
failure modes in the AGENT's responses.



Focus areas:
  - Factual errors (wrong office hours, wrong doctor availability, etc.)
  - Logical inconsistencies (booking a Sunday appointment when the office is closed)
  - Failure to handle edge cases gracefully (interruptions, unclear requests)
  - Inappropriate, unhelpful, or overly robotic responses
  - Failure to confirm or summarise important information (appointment time, date)
  - Privacy or safety concerns (sharing sensitive info, giving medical advice)
  - Conversation flow issues (not understanding context from earlier in the call)

ADDITIONAL ROBUSTNESS EVALUATION:

The patient is a test bot and may sometimes:
- Provide inconsistent information
- Interrupt or change details
- Repeat questions
- Be unclear or slightly contradictory
- Create edge-case conversational situations

Do NOT treat patient behavior as a bug.

Instead, evaluate whether the AGENT handled confusing or messy input
robustly and professionally.

If the AGENT fails to:
- Clarify inconsistencies
- Recover from interruptions
- Maintain context
- De-escalate conversational loops
- Summarize and re-anchor the conversation
- Gracefully handle unclear or contradictory input

Then flag it as a bug under the appropriate severity level.

Always focus on how the AGENT responded — never penalize the patient.

For each issue found, respond with a Markdown block in EXACTLY this format:

### Bug: <short title>
**Severity**: Critical | High | Medium | Low
**Timestamp**: [MM:SS] in the transcript
**Agent said**: "<exact quote from agent>"
**Problem**: <clear explanation of what went wrong>
**Expected**: <what the agent should have said or done>

If no issues are found, respond with: `No issues found.`

Do not include commentary outside of these blocks. Be specific - vague issues
are not actionable.
"""

#---------------------------------------------------------------------------
#QAAnalyzer: reads call transcripts and uses GPT-4o to identify and summarise bugs
#---------------------------------------------------------------------------
class QAAnalyzer:
    def __init__(self):
        self._client = AsyncOpenAI(api_key=settings.openai_api_key)
        REPORTS_DIR.mkdir(exist_ok=True)

    async def analyse_transcript(self, transcript_path: Path) -> str:
        try:
            transcript_text = transcript_path.read_text(encoding="utf-8")
        except IOError as exc:
            log.error("Cannot read transcript %s: %s", transcript_path, exc)
            return ""

        prompt = f"Transcript file: {transcript_path.name}\n\n{transcript_text}"

        try:
            response = await self._client.chat.completions.create(
                model=settings.openai_model,
                messages=[
                    {"role": "system", "content": _QA_SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                temperature=0,  
                max_tokens=1500,
            )
            return response.choices[0].message.content.strip()
        except Exception as exc:
            log.error("QA API error for %s: %s", transcript_path.name, exc)
            return f"*Analysis failed for {transcript_path.name}: {exc}*"

    #analyzing all transcripts in a directory and collate results into a single report.
    async def analyse_all(self, transcripts_dir: Path):
        transcript_files = sorted(transcripts_dir.glob("*.txt"))
        if not transcript_files:
            log.warning("No transcript files found in %s", transcripts_dir)
            return

        log.info("Analysing %d transcript(s)...", len(transcript_files))

        #Running all analyses concurrently 
        analyses = await asyncio.gather(
            *[self.analyse_transcript(tf) for tf in transcript_files]
        )

        #----Collate bug report ------------------------------------------------
        bug_report_path = REPORTS_DIR / "bug_report.md"
        with open(bug_report_path, "w", encoding="utf-8") as fh:
            fh.write("# Bug Report - PGAI Voice Agent QA\n\n")
            fh.write(
                "> Auto-generated by qa_analyzer.py. Review and trim before submitting.\n\n"
            )

            total_bugs = 0
            for transcript_path, analysis in zip(transcript_files, analyses):
                fh.write(f"---\n\n## {transcript_path.name}\n\n")
                fh.write(analysis + "\n\n")
                # Count bug blocks (each starts with "### Bug:")
                total_bugs += analysis.count("### Bug:")

        log.info("Bug report written → %s (%d issue(s))", bug_report_path, total_bugs)

        # ---- Run summary ------------------------------------------------------
        summary_path = REPORTS_DIR / "run_summary.md"
        with open(summary_path, "w", encoding="utf-8") as fh:
            fh.write("# Run Summary\n\n")
            fh.write(f"| Metric | Value |\n|--------|-------|\n")
            fh.write(f"| Calls completed | {len(transcript_files)} |\n")
            fh.write(f"| Issues found    | {total_bugs} |\n")
            fh.write(f"| Transcripts dir | `{transcripts_dir}` |\n")
            fh.write(f"| Bug report      | `{bug_report_path}` |\n\n")
            fh.write("## Calls\n\n")
            for tf in transcript_files:
                fh.write(f"- `{tf.name}`\n")

        log.info("Run summary written - %s", summary_path)
